import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';
import storeRoutes from './routes/store.js';
import searchRoutes from './routes/search.js';
import repoRoutes from './routes/repo.js';
import adminRoutes from './routes/admin.js';
import proxyRoutes from './routes/proxy.js';
import discoverCron from './cron/discover.js';
import enrichCron from './cron/enrich.js';
import snapshotCron from './cron/snapshot.js';
import trendingCron from './cron/trending.js';
import cleanupCron from './cron/cleanup.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json());
app.use('/api/store', storeRoutes);
app.use('/api/search', searchRoutes);
app.use('/api/repo', repoRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/proxy', proxyRoutes);
app.get('/api/cron/discover', discoverCron);
app.get('/api/cron/enrich', enrichCron);
app.get('/api/cron/snapshot', snapshotCron);
app.get('/api/cron/trending', trendingCron);
app.get('/api/cron/cleanup', cleanupCron);
if (process.env.NODE_ENV !== 'test') { app.listen(process.env.PORT || 3001, () => console.log(`OpenHub Backend listening on port ${process.env.PORT || 3001}`)); }
export default app;
